# Generated by Django 5.2.14 on 2026-05-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do cronograma')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('arquivado', 'Arquivado')], default='inativo', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('difficulty', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Dificuldade')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('goal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Meta de horas')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída')], default='ativa', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('planned_minutes', models.PositiveIntegerField(default=60, verbose_name='Tempo planejado (min)')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Horário previsto')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estudos.studyplan', verbose_name='Cronograma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='estudos.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Item do cronograma',
                'verbose_name_plural': 'Itens do cronograma',
                'ordering': ['day_of_week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('started_at', models.DateTimeField(verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('planned_minutes', models.PositiveIntegerField(default=0, verbose_name='Tempo planejado (min)')),
                ('gross_minutes', models.PositiveIntegerField(default=0, verbose_name='Tempo bruto (min)')),
                ('net_minutes', models.PositiveIntegerField(default=0, verbose_name='Tempo líquido (min)')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('encerrada', 'Encerrada pelo usuário')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='estudos.studyplanitem', verbose_name='Item do cronograma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='estudos.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Sessão de estudo',
                'verbose_name_plural': 'Sessões de estudo',
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Conteúdo estudado')),
                ('date', models.DateField(verbose_name='Data')),
                ('minutes_spent', models.PositiveIntegerField(default=0, verbose_name='Tempo dedicado (min)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='estudos.studysession', verbose_name='Sessão')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='estudos.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Conteúdo estudado',
                'verbose_name_plural': 'Conteúdos estudados',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Início da pausa')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim da pausa')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duração (min)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='estudos.studysession', verbose_name='Sessão')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='estudos.subject', verbose_name='Matéria ativa')),
            ],
            options={
                'verbose_name': 'Pausa',
                'verbose_name_plural': 'Pausas',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('duvida', 'Dúvida'), ('observacao', 'Observação'), ('pesquisa', 'Pesquisa'), ('resposta', 'Resposta de questionário')], max_length=15, verbose_name='Tipo')),
                ('text', models.TextField(verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='estudos.studysession', verbose_name='Sessão')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='estudos.subject', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Observação',
                'verbose_name_plural': 'Observações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('month', models.PositiveIntegerField(verbose_name='Mês')),
                ('total_minutes', models.PositiveIntegerField(default=0, verbose_name='Total de minutos estudados')),
                ('net_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutos líquidos')),
                ('total_pauses', models.PositiveIntegerField(default=0, verbose_name='Total de pausas')),
                ('pause_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutos de pausas')),
                ('efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Eficiência (%)')),
                ('procrastination_index', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Índice de procrastinação (%)')),
                ('study_days', models.PositiveIntegerField(default=0, verbose_name='Dias com estudo')),
                ('goals_hit', models.PositiveIntegerField(default=0, verbose_name='Metas de matérias atingidas')),
                ('report_json', models.JSONField(blank=True, default=dict, verbose_name='Dados completos (JSON)')),
                ('chart_path', models.CharField(blank=True, max_length=255, verbose_name='Caminho do gráfico gerado')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Gerado em')),
                ('most_studied_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_top', to='estudos.subject', verbose_name='Matéria mais estudada')),
            ],
            options={
                'verbose_name': 'Métrica mensal',
                'verbose_name_plural': 'Métricas mensais',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Início da semana')),
                ('week_end', models.DateField(verbose_name='Fim da semana')),
                ('total_minutes', models.PositiveIntegerField(default=0, verbose_name='Total de minutos estudados')),
                ('net_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutos líquidos')),
                ('total_pauses', models.PositiveIntegerField(default=0, verbose_name='Total de pausas')),
                ('pause_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutos de pausas')),
                ('efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Eficiência (%)')),
                ('procrastination_index', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Índice de procrastinação (%)')),
                ('study_days', models.PositiveIntegerField(default=0, verbose_name='Dias com estudo')),
                ('report_json', models.JSONField(blank=True, default=dict, verbose_name='Dados completos (JSON)')),
                ('chart_path', models.CharField(blank=True, max_length=255, verbose_name='Caminho do gráfico gerado')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Gerado em')),
                ('most_procrastinated_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_procrastinated', to='estudos.subject', verbose_name='Matéria mais procrastinada')),
                ('most_studied_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_top', to='estudos.subject', verbose_name='Matéria mais estudada')),
            ],
            options={
                'verbose_name': 'Métrica semanal',
                'verbose_name_plural': 'Métricas semanais',
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
