# Generated by Django 5.2.14 on 2026-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('encerrada', 'Encerrada pelo usuário'), ('pulada', 'Pulada')], default='em_andamento', max_length=20, verbose_name='Status'),
        ),
    ]
