# Generated by Django 5.2.6 on 2026-05-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0002_alter_studysession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='default_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Tempo padrão de sessão (min)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Peso (1–10)'),
        ),
    ]
