# Generated by Django 5.2.6 on 2026-05-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0003_subject_weight_default_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_discursiva',
            field=models.BooleanField(default=False, verbose_name='Discursiva'),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_oral',
            field=models.BooleanField(default=False, verbose_name='Oral'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.PositiveIntegerField(default=2, editable=False, verbose_name='Peso'),
        ),
    ]
