# Generated by Django 5.2.6 on 2026-05-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0004_add_discursiva_oral_to_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='certames',
            field=models.TextField(blank=True, verbose_name='Certames'),
        ),
    ]
